name: Ubuntu VNC

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop Environment & VNC
        run: |
          sudo apt update
          sudo apt install xfce4 xfce4-goodies tightvncserver git curl -y
          vncserver :1
          vncserver -kill :1
          mkdir -p ~/.vnc
          echo "#!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver :1 -geometry 1280x720 -depth 24

      - name: Setup noVNC + websockify
        run: |
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify ~/websockify
          nohup ~/websockify/run 6080 localhost:5901 &

      - name: Setup Cloudflare Tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          nohup ./cloudflared tunnel --url http://localhost:6080 --no-autoupdate &
          sleep 10
          echo "Open the logs below to find your public HTTPS link."
